apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp-deploy
  labels:
    app: myflaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myflaskapp
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
      - name: myflaskapp
        image: 915551958967.dkr.ecr.ap-south-1.amazonaws.com/flask_container:rmohan1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: myflaskapp-service
spec:
  type: NodePort
  selector:
    app: myflaskapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
